#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------

  
- name: Test for missing packages
  shell: dpkg --get-selections | grep aufs-tools | wc -l
  register: aufs

- shell: dpkg --get-selections | grep linux-image-extra | wc -l
  register: linux_image_extra

- shell: dpkg --get-selections | grep lxc-docker | awk {'print $2'} | grep -w install | wc -l
  register: lxc_docker

- command: uname -r
  register: uname
- apt: name=linux-image-extra-{{ uname.stdout_lines[0] }} update-cache=yes force=yes
  when: "'0' in linux_image_extra.stdout_lines[0]"

- apt: name=aufs-tools=1:3.2+20130722-1.1 update-cache=yes force=yes
  when: "'0' in aufs.stdout_lines[0]"

- name: Set Docker Ubuntu Repo Key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present
  ignore_errors: True
  when: "'0' in lxc_docker.stdout_lines[0]"
  
- name: Add Docker Apt repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
  when: "'0' in lxc_docker.stdout_lines[0]"
      
- name: Install Docker Client
  apt: name=lxc-docker=1.6.2 state=present update-cache=yes force=yes
  when: "'0' in lxc_docker.stdout_lines[0]"

# There seem to be a bug in the installation where config files are not installed.
# Might be a bug in the un-install where docket thinks it is upgrading.
# the below will overcome this as follows:
# If config files are installed we only change the default dir for docker data
# Otherwise, install the conf files from templates.
- stat: path=/etc/default/docker
  register: st1
- shell: grep {{ lxc_device }} /etc/default/docker | wc -l
  register: edited 
- name: Configure the Docker client to use the LXC block device.
  lineinfile: 
    dest: /etc/default/docker
    regexp: "^DOCKER_OPTS.*"
    line: DOCKER_OPTS="-g {{ lxc_device }}/docker --insecure-registry {{ groups['docker'][0]}}:{{ docker_registry_port }}"
    backup: yes
    state: present
  when: st1.stat.exists and '0' in edited.stdout 

# Hack to overcome installation problem where no conf files are installed
- stat: path=/etc/default/docker
  register: st2 
- name: Install docker defaults from template
  template: src=etc_default_docker dest=/etc/default/docker owner=root mode=0644
  when: not st2.stat.exists

# Hack to overcome installation problem where no conf files are installed
- stat: path=/etc/init/docker.conf
  register: st3 
- name: Install service config file from template
  template: src=etc_init_docker.conf dest=/etc/init/docker.conf owner=root mode=0755
  when: not st3.stat.exists

# Hack to overcome installation problem where no conf files are installed
- stat: path=/etc/init.d/docker
  register: st4
- name: Install initd config from template
  template: src=etc_init.d_docker dest=/etc/init.d/docker owner=root mode=0755 
  when: not st4.stat.exists

- name: Restart Docker Daemon
  shell: service docker stop ; sleep 1 ; service docker start
