#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------

- stat: path="{{ installation_dir }}"
  register: inst_dir
- command: mkdir -p {{ installation_dir }}
  when: not inst_dir.stat.exists

- name: clone repo
  stat: path="{{ installation_dir }}/{{swift_install_repo_name}}"
  register: repo_dir

- git: repo={{ swift_install_repo_url }}
       dest={{ installation_dir }}{{ swift_install_repo_name }}
  when: not repo_dir.stat.exists

- command: chmod 1777 "{{ installation_dir }}/{{swift_install_repo_name}}"

- command: ansible-playbook -s -i "{{ installation_dir }}/{{swift_install_repo_name}}/{{ swift_install_swift_config_dir}}/{{swift_install_dynamic_inventory }}" pull_keystone_service_module.yml
  args:
    chdir: "{{ installation_dir }}{{ swift_install_repo_name }}"
