#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------

- name: install python facade on host
  copy: src={{ SBusPythonFacade_dir }}/dist/{{ SBusPythonFacade_egg_dist }} dest=/tmp

- command: "tar -x --no-overwrite-dir --owner=root --group=root --mode=0755 --directory=/ --file=/tmp/{{ SBusPythonFacade_egg_dist }}"
- shell: rm /tmp/{{ SBusPythonFacade_egg_dist }}

- name: install sbus transport layer on host
  copy: src={{ SBusTransportLayer_dir }}/{{ sbus_so }} dest=/{{python_dist_packages_dir}} owner=root group=root mode=0755
        

- name: install swift middleware on host
  copy: src={{ swift_middleware_dir }}/dist/{{ swift_middleware_egg_dist }} dest=/tmp

- command: "tar -x --no-overwrite-dir --owner=root --group=root --mode=0755 --directory=/ --file=/tmp/{{ swift_middleware_egg_dist }}"
- shell: rm /tmp/{{ swift_middleware_egg_dist }}
             
- stat: path={{ lxc_device }}/scripts
  register: st
- name: Create scripts directory
  file: path="{{ lxc_device }}/scripts/" state=directory owner=swift group=swift mode=0755
  when: not st.stat.exists
  
- name:  install runtime scripts used by swift middleware
  copy:
    src: "{{ storlet_source_dir }}/{{ item }}"
    dest:  "{{ lxc_device }}/scripts/"
    mode: "04755"
  with_items:
    - "Engine/SMScripts/bin/restart_docker_container"
    - "Engine/SMScripts/send_halt_cmd_to_daemon_factory.py"
- name: create installation directory
  shell: mkdir -p {{ engine_install_dir  }} creates={{ engine_install_dir  }}

- name: Copy Swift middleware conf template
  template: 
    src: ../../common_templates/swift_middleware_conf
    dest: "{{ engine_install_dir  }}"
    owner: swift
    group: swift
    mode: 0644


- name: copy install script
  copy: src="{{ item }}" dest={{ engine_install_dir  }}
  with_items:
   - ../../common_files/swift_config.py
   
- name: Copy gateway conf template
  template: 
    src: "{{ swift_middleware_dir }}/etc/storlet-docker-gateway.conf-sample"
    dest: "{{ storlet_gateway_conf_file }}"
    owner: swift
    group: swift
    mode: 0644

- name: configure swift
  shell: chdir={{ engine_install_dir  }}
         python swift_config.py install swift_middleware_conf

- name: restart swift
  shell: swift-init all restart
  ignore_errors: yes
