#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------


# A cross nodes directory for Storlets internal usage. Must exist with the same name in all proxy and storage nodes.
lxc_device: /home/lxc_device
# A pointer to this repo
storlet_source_dir: <Set Me!>

#----------------------------------------------------------------
# Swift Access information. The below IP should be an IP of one of the proxies.
swift_endpoint_host: <Set Me!>
swift_public_url: http://{{ swift_endpoint_host }}:80/v1

# Keystone access information
keystone_endpoint_host: <Set Me!>
keystone_admin_url: http://{{ keystone_endpoint_host }}:35357/v2.0
keystone_public_url: http://{{ keystone_endpoint_host }}:5000/v2.0
keystone_admin_token: ADMIN
keystone_admin_password: passw0rd
#----------------------------------------------------------------

#----------------------------------------------------------------
# Information for creating an account for the Storlet manager
storlet_management_account: storlet_management
storlet_management_admin_username: storlet_manager
storlet_manager_admin_password: storlet_manager
storlet_management_swift_topology_container: swift_cluster
storlet_management_swift_topology_object : swift_cluster_nodes

# Additional Storlet management installation information
storlet_management_ansible_dir: /opt/ibm/ansible/playbook
storlet_management_install_dir: /opt/ibm

# The below attribute can take true / false
storlets_enabled_attribute_name: storlet-enabled
#----------------------------------------------------------------

#----------------------------------------------------------------
# Information for creating a Storlet enabled account
storlets_default_tenant_name: service
storlets_default_tenant_user_name: swift
storlets_default_tenant_user_password: passw0rd
#----------------------------------------------------------------

#----------------------------------------------------------------
# docker_repository / docker_registry 
docker_registry_random_string: ABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJ1234
docker_registry_port: 5001
#----------------------------------------------------------------

#----------------------------------------------------------------
# docker_base_storlet_images / docekr_base_images 
ibm_container_install_dir: opt/ibm
base_image_maintainer: root
base_os_image: ubuntu_14.04
storlets_image_name_suffix: ubuntu_14.04_jre7_storlets
swift_user_id: 1003
swift_group_id: 1003
#----------------------------------------------------------------

#----------------------------------------------------------------
python_dist_packages_dir: usr/local/lib/python2.7/dist-packages
storlet_gateway_conf_file: /etc/swift/storlet_docker_gateway.conf
#----------------------------------------------------------------
