- name: ensure storlets aio dependencies are installed
  shell: apt-cache showpkg ansible | grep 1.9.1-1ppa~trusty | wc -l
  register: add_repo

- apt_repository: repo='ppa:ansible/ansible' state=present
  when: "'0' in add_repo.stdout_lines[0]"

- apt:
    pkg: ansible=1.9.1-1ppa~trusty
    force: yes
    update_cache: yes

- apt:
    pkg: "{{ item }}"
    state: latest
    force: yes
    update_cache: yes
    cache_valid_time: 600
  with_items: packages

